package CPANMonitor::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'CPANMonitor::Schema',
    
    connect_info => {
        dsn => 'dbi:mysql:cpanmonitor_dev',
        user => 'cpanmonitor_dev',
        password => 'cpanmonitor_dev',
        AutoCommit => q{1},
    }
);

=head1 NAME

CPANMonitor::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<CPANMonitor>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<CPANMonitor::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.44

=head1 AUTHOR

A clever guy

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
